<?php echo $this->doctype() ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>

    <?php echo $this->headMeta() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <?php echo $this->placeholder('html5js') ?>

    <![endif]-->

    <?php echo $this->headScript() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <?php echo $this->placeholder('favicon') ?>

  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">Nennius</a>

          <ul class="nav">
            <li <?php /*class="active" */?>><a href="<?php echo $this->url('home') ?>">Home</a></li>
            <?php if($this->edpUser()): ?>
            <li><a href="<?php echo $this->url('edpuser/logout') ?>">Logout</a></li>
            <?php else : ?>
            <li><a href="<?php echo $this->url('edpuser/login') ?>">Login</a></li>
            <?php endif; ?>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->raw('content'); ?>

      <footer>
        <p>&copy; 2011 <?php echo date('Y') != 2011 ?  '-'.date('Y') : ''; ?> by Rob Allen. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
