<?php 
$this->headTitle()->setSeparator(' - ');
$this->headTitle()->setAutoEscape(false);

$basePath = $this->basePath();
$this->plugin('headLink')->appendStylesheet($basePath . '/css/bootstrap.min.css');
$this->plugin('headLink')->appendStylesheet($basePath . '/css/site.css');
$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Nennius') ?>

    <?php echo $this->headMeta() ?>

    <!-- JS -->
    <?php echo $this->headScript() ?>


    <!-- Styles -->
    <?php echo $this->headLink() ?>


  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">Nennius</a>

          <ul class="nav">
            <li <?php /*class="active" */?>><a href="<?php echo $this->url('home') ?>">Home</a></li>
            <li><a href="<?php echo $this->url('photos/upload') ?>">Upload</a></li>
            <?php if($this->zfcUserIdentity()): ?>
            <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
            <?php else : ?>
            <li><a href="<?php echo $this->url('zfcuser/login') ?>">Login</a></li>
            <?php endif; ?>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <?php //echo $this->raw('content'); ?>
      <?php echo $this->content; ?>
      <?php //echo $this->placeholder('content') ?>

      <footer>
        <p>&copy; 2011<?php echo date('Y') != 2011 ?  ', '.date('Y') : ''; ?> by Rob Allen. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
