<div class="hero-unit">
    <h1>Latest photos</h1>
</div>

<?php foreach($latest as $photo) : ?>
<div class="thumbnail">
    <div class="title"><a href=""><?php echo $photo->getTitle();?></a></div>
    <a href=""><img src="<?php $photo->thumbnailUrl(200, 200, 'square'); ?>" /></a>
    <div class="description"><?php echo $this->escape($photo->getDescription());?></div>
</div>
<?php endforeach; ?>

