<?php $this->headTitle('Latest'); ?>

<div class="hero-unit">
    <h1>Latest photos</h1>
</div>

<?php foreach($latest as $photo) : ?>
<div class="thumbnail">
    <h2><a href=""><?php echo $photo->getTitle();?></a></h2>
    <a href=""><?php echo $this->galleryThumbnail($photo, 500, 500, 'bounding'); ?></a>
    <div class="description"><?php echo $this->escape($photo->getDescription());?></div>


    <hr>
</div>
<?php endforeach; ?>

